### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/github-stats#20]
We currently have the default Vercel icon, I'd like to replace it.

Maybe we shouldn't use the GitHub icon as it can be misleading... I'm open to suggestions :D

**Comment by pavelee** [comment]
it should be ⭐️ until we find any other idea

**Comment by Balastrong** [comment]
Yeah, I agree on the star @pavelee for now and I see we already have #35 to add it in the code, that's great!

Anyway, if while building the project we come up with a more relevant and distinctive icon I'll be more than happy to evaluate it :)
