### ISSUE TITLE
PR status indicator takes full height

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/github-stats#22]
The PR status indicator takes the full height, we should fix it to have its background only behind the text

<img width="944" alt="image" src="https://github.com/Balastrong/github-stats/assets/7253929/05088ca7-036b-4ea2-965d-aa8feea32ba2">

**Comment by theanantchoubey** [comment]
I want to work on this issue.
Requesting to get assigned it.

**Comment by Balastrong** [comment]
Thanks!

I assigned the issue :)
