### ISSUE TITLE
Export button in text mode is inside the next container

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/github-stats#38]
**Bug description**

The export button seems to be inside the `<pre>` tag

**Reproduction steps**
1. Open the stats page
2. Go on "Text" mode

**Expected behavior**
The button is before the text, outside the `<pre>` tag

**Screenshots**
![image](https://github.com/Balastrong/github-stats/assets/7253929/16940620-0642-4e11-9223-ec02c9ad7ce7)

**Additional context**

As a https://github.com/Balastrong/github-stats/labels/good%20first%20issue I will be really happy if this is taken by a first time contributor :)

**Comment by jakubfronczyk** [comment]
Hello, I'm looking for my first time contribution. Could i take this issue ?

**Comment by Balastrong** [comment]
Hey @jakubfronczyk, welcome!

Sure, I assigned the issue to you :)

**Comment by Balastrong** [comment]
Done in #44
