### ISSUE TITLE
Bug: Background color is limited to the screen size only

### ISSUE THREAD

**Issue by theanantchoubey** [Balastrong/github-stats#42]
**Bug description**
Background height is fixed to 100% only, which leads to the background color filling until the screen's size only.

**Reproduction steps**

1. Go to the home page
2. Scroll down
3. You will see a partition of 2 colors, a black and a grey

[Alternatively]
1. Go to your Stats Page
2. Check your stats in a format where the size of the screen exceeds
3. Scroll down and you will notice the issue

**Expected behavior**
The background color should be there until the bottom of the page.

**Screenshots**
- Check the bottom of the Screenshot

![temp](https://github.com/Balastrong/github-stats/assets/91460022/cd97c8ae-4ee4-4cb1-b3bf-cb54527494fa)

**Additional context**
- [x]  I make sure that a similar issue is not opened
- [x] I would like to work on this issue.

**Comment by theanantchoubey** [comment]
Thanks for Checking out!
In the case of my issue, the root cause is the height set to 100%.
But in the #41 case, the data is overflowing, what are your thoughts on its cause? 
Note: I tried fixing my issue but it is not fixing #41

**Comment by Balastrong** [comment]
Ok then, we can keep them separate :)
