### ISSUE TITLE
Add description how to setup development environment 

### ISSUE THREAD

**Issue by pavelee** [Balastrong/github-stats#46]
**Feature Description**

Description how to setup development environment 

**It should be implemented because...**

To clarify how to run app for development, especially part about your GitHub token required to signing

**Describe alternatives you've considered**

Could be something like https://github.com/facebook/docusaurus but at this moment description in README is enough

**Additional context**

I spend some extra time to figure out how to singing on development environment

**Comment by Balastrong** [comment]
If you think something is missing or is not clear enough, feel free to open a PR or an issue to discuss it :)
