### ISSUE TITLE
Spacing between export buttons is inconsistent

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/github-stats#58]
### Describe your issue

When I change display mode, I see that the export button for Cards is spaced evenly on top and bottom, but the export buttons for Text and Json have an extra space on top

### Steps to reproduce

1. Login
2. Go on the Stats page
3. Change display mode

### What was the expected result?

Spacing is the same for all three buttons

### Put here any screenshots or videos (optional)

![image](https://github.com/Balastrong/github-stats/assets/7253929/ab5f65ae-7cc7-4ba1-bd6b-fa730850228f)
![image](https://github.com/Balastrong/github-stats/assets/7253929/119881ae-0a27-44a5-91da-3b0bbbc4da63)
![image](https://github.com/Balastrong/github-stats/assets/7253929/ab8997cb-9045-4544-aaa0-5177e1c6a70d)

### Extra fields

- [X] I have used the search function to check if an issue already exists
- [ ] I'd like to work on this issue

**Comment by luckyklyist** [comment]
I believe these issues are no longer occurring. I think they have already been fixed, if I am not mistaken.

**Comment by Balastrong** [comment]
> I believe these issues are no longer occurring. I think they have already been fixed, if I am not mistaken.

Ah yes, it was fixed with #61, we can close the issue. Thank you!
