### ISSUE TITLE
Add text filter

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/github-stats#59]
### Describe the feature

Add a text input to filter repositories on the stats page

### It should be implemented because

The filter allows to easily find a repository

### Additional context

Should only filter locally, there's no need to call the API again as we expect all repositories to be there already

### Extra fields

- [X] I have used the search function to check if an issue already exists
- [ ] I'd like to work on this issue

**Comment by luckyklyist** [comment]
I will liked to work on this issues .

**Comment by Balastrong** [comment]
@luckyklyist sure! Go ahead :)

**Comment by luckyklyist** [comment]
@Balastrong, I have sent a PR. I'm waiting for your review. Are there any improvements needed in the UI or the code part? Please let me know.
