### ISSUE TITLE
chore: add cursor pointer

### ISSUE THREAD

**Issue by priyankarpal** [Balastrong/github-stats#65]
### Describe your issue

just need to add a cursor pointer to the `Export as image` button

### Steps to reproduce

.

### What was the expected result?

.

### Put here any screenshots or videos (optional)

![image](https://github.com/Balastrong/github-stats/assets/88102392/6bacb610-dadc-4b16-bef1-b9b81379268c)

### Extra fields

- [X] I have used the search function to check if an issue already exists
- [X] I'd like to work on this issue

**Comment by Balastrong** [comment]
Feel free to work on it if you want :)

**Comment by priyankarpal** [comment]
sure!
