### ISSUE TITLE
Feat : Clipboard Img copy alert 

### ISSUE THREAD

**Issue by luckyklyist** [Balastrong/github-stats#71]
### Describe the feature

An alert to be displayed to the user after they have copied the image to the clipboard.

### It should be implemented because

It would be good for the User experience . 

### Additional context

<img width="339" alt="Screenshot 2023-10-02 at 6 37 40 PM" src="https://github.com/Balastrong/github-stats/assets/35479077/f5c3bddd-cfcc-4acd-bee7-1091c16c7e44">

### Extra fields

- [X] I have used the search function to check if an issue already exists
- [X] I'd like to work on this issue

**Comment by Balastrong** [comment]
Done with #72
