### ISSUE TITLE
feat: add repository link to the card title

### ISSUE THREAD

**Issue by priyankarpal** [Balastrong/github-stats#9]
currently we have added only repository url & owner name also, we can insert the repository url there. It will help owners to navigate to the repo. 

Also, I have added `hover:underline` 

## After changes 

https://github.com/Balastrong/github-stats/assets/88102392/2fa43d72-a749-4f8d-a3ea-94b7f44af81b

what do you think @Balastrong ? if you want I will raise the PR

**Comment by Balastrong** [comment]
Nice! Yes, please open the PR :)
